// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    url: {
      base: 'https://aur.archlinux.org/',
      info: 'rpc.php?type=info&arg=',
      post: 'pkgsubmit.php'
    }
  };

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
